# Generated by Django 5.1.6 on 2025-03-19 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('is_del', models.SmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dot_s', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'db_table': 'dot',
            },
        ),
        migrations.CreateModel(
            name='DotDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('is_del', models.SmallIntegerField(default=0)),
                ('dot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='dot.dot', verbose_name='所属点')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dot_details', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'db_table': 'dot_detail',
            },
        ),
    ]
