# Generated by Django 3.2 on 2025-03-10 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('answer_image_url', models.CharField(blank=True, max_length=200, null=True)),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('is_del', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='QuizChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=200)),
                ('is_true', models.BooleanField(default=False)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quiz.quiz', verbose_name='题目')),
            ],
        ),
        migrations.CreateModel(
            name='QuizCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='题目分类')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('is_del', models.SmallIntegerField(default=0)),
                ('quiz_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_categories', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_s', to='quiz.quizcategory', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_s', to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
    ]
