# Generated by Django 5.1.6 on 2025-02-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.SmallIntegerField(default=0, help_text='0: 只是提交, 1: 注册成功, 验证通过'),
        ),
    ]
