# Generated by Django 5.1.6 on 2025-02-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
