# Generated by Django 5.1.6 on 2025-02-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='create_datetime',
            field=models.DateTimeField(),
        ),
    ]
